---
engines:
  fixme:
    enabled: true
    exclude_fingerprints:
    - c42b72af850c2590419dfa0bb4d15004
    - b86af833d6b2b1fa18da63471e2278d9
    - cdc1cac1f5cb7afe72dca9f9bca8a237
    - ee0a31701f95b21db4aff40647a56a3d
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- test/**/*
